version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: inbox_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: pressly/goose:latest
    depends_on:
      - postgres
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgresql://admin:пароль@postgres:5432/payments-service-db?sslmode=disable
    volumes:
      - ./migrations:/migrations
    command: up
    restart: on-failure

volumes:
  postgres_data: